In [1]:
import trimesh
import numpy as np
mesh = trimesh.load('005_tomato_soup_can_textured.obj')

unable to load materials from: 005_tomato_soup_can_textured.mtl
specified material (material_0)  not loaded!


In [2]:
default_T = mesh.bounding_box_oriented.primitive.transform

In [3]:
inv_T = np.linalg.inv(default_T)

In [4]:
print("default tranformation \n", np.round(default_T,2))

default tranformation 
 [[ 0.33 -0.94 -0.   -0.01]
 [-0.94 -0.33 -0.    0.08]
 [ 0.    0.   -1.    0.05]
 [ 0.    0.    0.    1.  ]]


In [5]:
print("inverse tranformation \n", np.round(inv_T,2))

inverse tranformation 
 [[ 0.33 -0.94  0.    0.08]
 [-0.94 -0.33  0.    0.02]
 [-0.   -0.   -1.    0.05]
 [ 0.    0.    0.    1.  ]]


In [6]:
new_mesh = mesh.copy()
new_mesh=new_mesh.apply_transform(inv_T)
new_T = new_mesh.bounding_box_oriented.primitive.transform

In [7]:
print("new transformation \n", np.round(new_T,2))

new transformation 
 [[-1.  0. -0. -0.]
 [ 0.  1.  0. -0.]
 [-0. -0. -1.  0.]
 [ 0.  0.  0.  1.]]


In [8]:
print("product new T vs default T \n", np.round(np.dot(new_T, default_T),2))

product new T vs default T 
 [[-0.33  0.94  0.    0.01]
 [-0.94 -0.33 -0.    0.08]
 [-0.   -0.    1.   -0.05]
 [ 0.    0.    0.    1.  ]]


In [9]:
print("product inv T vs default T \n", np.round(np.dot(inv_T, default_T),2))

product inv T vs default T 
 [[ 1.  0.  0. -0.]
 [ 0.  1. -0.  0.]
 [-0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
